using Newtonsoft.Json.Linq;

namespace PodcastService.Infrastructure.Models.Kafka
{
    // To start a flow by sending messageType == flow name (handled by FlowMessageHandler).
    // No SagaId here; the receiving handler will generate a new one.
    public class StartSagaTriggerMessage : BaseMessage
    {
        public Guid SagaId { get; set; } = Guid.Empty; // New SagaId will be generated by the handler
        public string MessageName { get; set; } = string.Empty;
        public JObject RequestData { get; set; } = new();
    }
}
